version: '3.7'

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        entrypoint: ['sh', '/usr/quotation/server/app.sh']
        volumes:
            - '.:/usr/quotation/server'
        ports:
            - 5001:5000