version: '3.7'

services:
    api:
        build:
            context: ./services/server
            dockerfile: Dockerfile
        entrypoint: ['sh', '/usr/quotation/server/app.sh']
        volumes:
            - './services/server:/usr/quotation/server'
        ports:
            - 5001:5000